### PR TITLE
Add web3pay billing middleware

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: all files reviewed, 8 unresolved discussions (waiting on @wanliqun)

___
*[`rpc/server_middleware.go` line 30 at r2](https://reviewable.io/reviews/conflux-chain/confura/14#-N9peFhc16xZ7UR-ZJfN:-N9peFhc16xZ7UR-ZJfO:bysuqhv) ([raw file](https://github.com/conflux-chain/confura/blob/9d43c25d902da84966e9455b539b2aba14b9190e/rpc/server_middleware.go#L30)):*
> ```Go
> 	web3payMwProvider, ok := middlewares.MustNewWeb3PayMiddlewareProvider()
> 	if ok { // enabled?
> 		rpc.HookHandleBatch(web3payMwProvider.BillingBatchMiddleware)
> ```

Why need billing middleware for batch hook?
___
*[`util/rpc/handlers/ip.go` line 130 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9paytxDDt6Mk1rA55b:-N9paytxDDt6Mk1rA55c:btof8oy) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/handlers/ip.go#L130)):*
> ```Go
> 
> func GetWeb3PayCustomerKey(r *http.Request) string {
> 	return r.URL.Query().Get("web3pay_customer_key")
> ```

`key` is enough for web3pay service. What's more, we should compatible with ETH infura way, e.g. `https://domain.com/{key}`.



_Code quote:_
```Go
web3pay_customer_key
```
___
*[`util/rpc/middlewares/billing.go` line 12 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pb6wDD_45aCrl48tS:-N9pb6wDD_45aCrl48tT:b-8201lr) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L12)):*
> ```Go
> )
> 
> type web3PayConfig struct {
> ```

Why not define in web3pay service?



_Code quote:_
```Go
web3PayConfig
```
___
*[`util/rpc/middlewares/billing.go` line 16 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pd1Iy8vvnZjOl5iEV:-N9pd1Iy8vvnZjOl5iEW:bd9hde0) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L16)):*
> ```Go
> 	BillingKey      string
> 	GatewayEndpoint string
> 	RequestTimeout  time.Duration `default:"1s"`
> ```

1s is too long for internal service, 200ms is enough.
___
*[`util/rpc/middlewares/billing.go` line 24 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pbG6cBg3UackPy5Dd:-N9pbG6cBg3UackPy5De:b-6v1t2q) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L24)):*
> ```Go
> 
> 	if !config.Enabled {
> 		logrus.Info("Web3pay billing RPC middleware not enabled")
> ```

`Debug` level is enough. `Info` is required only when billing middleware configured.
___
*[`util/rpc/middlewares/billing.go` line 33 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdY2V8Sq8N4kzR7LU:-N9pdY2V8Sq8N4kzR7LV:b-hsqxfr) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L33)):*
> ```Go
> 			Timeout:     config.RequestTimeout,
> 			BillingKey:  config.BillingKey,
> 			CustomerKey: handlers.GetWeb3PayCustomerKeyFromContext,
> ```

The value is a func, not a key. Suggest to use a meaningful variable name.



_Code quote:_
```Go
CustomerKey
```
___
*[`util/rpc/middlewares/billing.go` line 35 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdsT_758c5xQ5h_8G:-N9pdsT_758c5xQ5h_8H:b2kz6v2) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L35)):*
> ```Go
> 			CustomerKey: handlers.GetWeb3PayCustomerKeyFromContext,
> 			// rate limit is used as fallback for billing middleware.
> 			BillingFallbackMw:      RateLimit,
> ```

It does not make sense to limit users due to our internal error.
___
*[`util/rpc/middlewares/billing.go` line 36 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pe-Bi-7jGXHba8nbT:-N9pe-Bi-7jGXHba8nbU:b-p6rznb) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L36)):*
> ```Go
> 			// rate limit is used as fallback for billing middleware.
> 			BillingFallbackMw:      RateLimit,
> 			BillingBatchFallbackMw: RateLimitBatch,
> ```

Why need billing for batch rpc?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @boqiu)

___
*[`rpc/server_middleware.go` line 30 at r2](https://reviewable.io/reviews/conflux-chain/confura/14#-N9peFhc16xZ7UR-ZJfN:-NA3nK8c5-M9R4NsAY24:b3z199f) ([raw file](https://github.com/conflux-chain/confura/blob/9d43c25d902da84966e9455b539b2aba14b9190e/rpc/server_middleware.go#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why need billing middleware for batch hook?
</blockquote></details>

For batch ratelimit reason. Anyway, it's removed now after discussion.
___
*[`util/rpc/handlers/ip.go` line 130 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9paytxDDt6Mk1rA55b:-NA3nbLB8d0-UP6WURWH:bb7f2mf) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/handlers/ip.go#L130)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`key` is enough for web3pay service. What's more, we should compatible with ETH infura way, e.g. `https://domain.com/{key}`.
</blockquote></details>

done
___
*[`util/rpc/middlewares/billing.go` line 12 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pb6wDD_45aCrl48tS:-NA3njK4BerUoD73O2Dm:bb7f2mf) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L12)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not define in web3pay service?
</blockquote></details>

done
___
*[`util/rpc/middlewares/billing.go` line 16 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pd1Iy8vvnZjOl5iEV:-NA3nk99BSEfPVy1_xmt:bb7f2mf) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1s is too long for internal service, 200ms is enough.
</blockquote></details>

done
___
*[`util/rpc/middlewares/billing.go` line 24 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pbG6cBg3UackPy5Dd:-NA3nle33eWTRt6SDCGA:bb7f2mf) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`Debug` level is enough. `Info` is required only when billing middleware configured.
</blockquote></details>

done
___
*[`util/rpc/middlewares/billing.go` line 33 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdY2V8Sq8N4kzR7LU:-NA3o2Nv7BRfnTqw1CH7:bb7f2mf) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L33)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

The value is a func, not a key. Suggest to use a meaningful variable name.
</blockquote></details>

done
___
*[`util/rpc/middlewares/billing.go` line 35 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdsT_758c5xQ5h_8G:-NA3o4Py4YSYU78mUGUY:b-q84vhb) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

It does not make sense to limit users due to our internal error.
</blockquote></details>

Seems reasonable if not billed, otherwise let's say what if our web3pay gateway crashed down, all requests would bypass our ratelimit strategies, and cause severe workload to our API service.
___
*[`util/rpc/middlewares/billing.go` line 36 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pe-Bi-7jGXHba8nbT:-NA3owacA023vfGgpGx-:b-veswfv) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L36)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why need billing for batch rpc?
</blockquote></details>

ditto. Removed.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[`util/rpc/middlewares/billing.go` line 35 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdsT_758c5xQ5h_8G:-NA3tdky0TjH5wfyV4oY:beulrin) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L35)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Seems reasonable if not billed, otherwise let's say what if our web3pay gateway crashed down, all requests would bypass our ratelimit strategies, and cause severe workload to our API service.
</blockquote></details>

First of all, we should not block VIP users due to internal errors. It's up to API provider to fix the issue timely. As a bonus, we could simply allow users to still access API without billing.

What's more, there could be option to indicate the expected behavior when web3pay service unavailable.
___
*[`util/rpc/middlewares/billing.go` line 17 at r3](https://reviewable.io/reviews/conflux-chain/confura/14#-NA3tAZuDIaB_V16Rsf8:-NA3tAZuDIaB_V16Rsf9:b-edk2oc) ([raw file](https://github.com/conflux-chain/confura/blob/214b962bd62465721803e004e45e90ffe558b3ad/util/rpc/middlewares/billing.go#L17)):*
> ```Go
> 		web3pay.ClientConfig `mapstructure:",squash"`
> 		Enabled              bool
> 		Timeout              time.Duration `default:"200ms"`
> ```

Any difference with `web3pay.ClientConfig.Timeout`?



_Code quote:_
```Go
Timeout
```

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`util/rpc/middlewares/billing.go` line 35 at r1](https://reviewable.io/reviews/conflux-chain/confura/14#-N9pdsT_758c5xQ5h_8G:-NA8E1mR1jGQUhoS3z8y:b-6u9d3i) ([raw file](https://github.com/conflux-chain/confura/blob/d59429da69695d045144f2b29feb1d6702136365/util/rpc/middlewares/billing.go#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

First of all, we should not block VIP users due to internal errors. It's up to API provider to fix the issue timely. As a bonus, we could simply allow users to still access API without billing.

What's more, there could be option to indicate the expected behavior when web3pay service unavailable.
</blockquote></details>

Now the billing result has been set within the context by middleware. The API provider can extract the billing status from the context, then do some checkings such as if billing succeeded or internal server error encountered, and finally do some custom handling.
___
*[`util/rpc/middlewares/billing.go` line 17 at r3](https://reviewable.io/reviews/conflux-chain/confura/14#-NA3tAZuDIaB_V16Rsf8:-NA7Wvwi7LHjaCY6w1Ip:bqj2o6q) ([raw file](https://github.com/conflux-chain/confura/blob/214b962bd62465721803e004e45e90ffe558b3ad/util/rpc/middlewares/billing.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Any difference with `web3pay.ClientConfig.Timeout`?
</blockquote></details>

200ms default timeout has been set within web3pay.ClientConfig now.

**Review by boqiu — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @boqiu)

**Review by wanliqun — COMMENTED** [review]
The skipping internal gateway server error logic has been encapsulated within the middleware now:
https://github.com/Conflux-Chain/web3pay-service/commit/6ce5ea6a21f2def44ebdab7a07e336840dd2c7cc

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14#-:-NA9HTblBu3cD8JLhlQm:ba12u34)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @boqiu)

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
