### PR TITLE
Add shared proxy filter to poll filter changes from full node

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: all files reviewed, 3 unresolved discussions (waiting on @wanliqun)

___
*[`virtualfilter/proxy.go` line 17 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzLubl-WKXTyqswBjv:-NGzLubl-WKXTyqswBjw:bmfox1s) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L17)):*
> ```Go
> 
> // proxyContext context for shared proxy filter to the full node
> type proxyContext struct {
> ```

Is it possible to merge with `delegateContext` below?



_Code quote:_
```Go
proxyContext
```
___
*[`virtualfilter/proxy.go` line 18 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzSyWo65FVjsfEs4Wp:-NGzSyWo65FVjsfEs4Wq:b-vhyizs) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L18)):*
> ```Go
> // proxyContext context for shared proxy filter to the full node
> type proxyContext struct {
> 	mu  sync.Mutex
> ```

It is not a good practice to define a `mutex` here, but used in any other place.
___
*[`virtualfilter/proxy.go` line 71 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzJm2p6QG7luQJAkMp:-NGzJm2p6QG7luQJAkMq:bh3b8f9) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L71)):*
> ```Go
> func (dctx *delegateContext) close() {
> 	if !dctx.closed {
> 		close(dctx.termCh)
> ```

How about to set `termCh` to nil and depends on `termCh` to check if closed already?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @boqiu)

___
*[`virtualfilter/proxy.go` line 17 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzLubl-WKXTyqswBjv:-NGzlbiV2XbTcCR2lRlL:b-9pbp0w) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to merge with `delegateContext` below?
</blockquote></details>

Afraid not. `delegateContext` is  per proxy filter, while `proxyContext` is per full node.
___
*[`virtualfilter/proxy.go` line 18 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzSyWo65FVjsfEs4Wp:-NGzls7NBLtvdzFx2jOP:b-896fix) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

It is not a good practice to define a `mutex` here, but used in any other place.
</blockquote></details>

Done.
___
*[`virtualfilter/proxy.go` line 71 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzJm2p6QG7luQJAkMp:-NGzlt-hBrMbfPzmbyvh:b-896fix) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L71)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to set `termCh` to nil and depends on `termCh` to check if closed already?
</blockquote></details>

Done.

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @boqiu)

___
*[`virtualfilter/proxy.go` line 17 at r1](https://reviewable.io/reviews/conflux-chain/confura/46#-NGzLubl-WKXTyqswBjv:-NH3C0lZDMG_nvqUr9NK:bb6un1j) ([raw file](https://github.com/conflux-chain/confura/blob/06445fd408f544ed49f7480ddff16ecb526d8fd5/virtualfilter/proxy.go#L17)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Afraid not. `delegateContext` is  per proxy filter, while `proxyContext` is per full node.
</blockquote></details>

Done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`virtualfilter/filter_system.go` line 40 at r2](https://reviewable.io/reviews/conflux-chain/confura/46#-NH7TXtbDCy0ERR4I4G9:-NH7TXtbDCy0ERR4I4GA:b-z9pll8) ([raw file](https://github.com/conflux-chain/confura/blob/2070d5a18663e05e2e48f15fb119104f71f98901/virtualfilter/filter_system.go#L40)):*
> ```Go
> 	// There would be one mutex per full node for operations such as establishing proxy filter etc.
> 	// to reduce lock waits by seperation from different full nodes.
> 	proxyLocks util.ConcurrentMap // node name => *sync.Mutex
> ```

Is it possible to merge with the `proxyContext`? In my mind, you could define `proxyContext` as a thread-safe object.

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`virtualfilter/filter_system.go` line 40 at r2](https://reviewable.io/reviews/conflux-chain/confura/46#-NH7TXtbDCy0ERR4I4G9:-NH8ZFRqE5go6jcUEsrI:b-896fix) ([raw file](https://github.com/conflux-chain/confura/blob/2070d5a18663e05e2e48f15fb119104f71f98901/virtualfilter/filter_system.go#L40)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to merge with the `proxyContext`? In my mind, you could define `proxyContext` as a thread-safe object.
</blockquote></details>

Done.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`virtualfilter/proxy.go` line 61 at r3](https://reviewable.io/reviews/conflux-chain/confura/46#-NH8nE2_CT82ry6YwkUf:-NH8nE2_CT82ry6YwkUg:b-lbnei3) ([raw file](https://github.com/conflux-chain/confura/blob/0c170efefe6cffe4e09915b8c026cf1303130f50/virtualfilter/proxy.go#L61)):*
> ```Go
> 	// snapshot shared filter cursor
> 	p.pctx.delegates[dfid] = &FilterContext{
> 		cursor: p.pctx.cur, crit: crit,
> ```

memory copy of `cur` required for each client?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`virtualfilter/proxy.go` line 61 at r3](https://reviewable.io/reviews/conflux-chain/confura/46#-NH8nE2_CT82ry6YwkUf:-NH8ueOx-cp4Vtu3rpjp:b-896fix) ([raw file](https://github.com/conflux-chain/confura/blob/0c170efefe6cffe4e09915b8c026cf1303130f50/virtualfilter/proxy.go#L61)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

memory copy of `cur` required for each client?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
