### PR TITLE
Extract common base of time window operation for metrics

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: all files reviewed, 4 unresolved discussions (waiting on @wanliqun)

___
*[`util/metrics/time_window.go` line 11 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8LmvN1p06j2JoN3Cg:-NQ8LmvN1p06j2JoN3Ch:b-c1e0qg) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L11)):*
> ```Go
> 
> // slot slot sliced for time-based window
> type slot interface {
> ```

Is this interface required?



_Code quote:_
```Go
slot
```
___
*[`util/metrics/time_window.go` line 18 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8MURQ6Q2JSIVaOi-A:-NQ8MURQ6Q2JSIVaOi-B:bfr5hxs) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L18)):*
> ```Go
> 
> type slotContext struct {
> 	endTime  time.Time // slot end time
> ```

Not used?



_Code quote:_
```Go
endTime
```
___
*[`util/metrics/time_window.go` line 23 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8M-yj5LlgMAH56lPv:-NQ8M-yj5LlgMAH56lPw:b98zh3e) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L23)):*
> ```Go
> 
> func (ctx slotContext) expired(now time.Time) bool {
> 	return !ctx.expireAt.After(now)
> ```

Why not use `Before` instead of `After`?
___
*[`util/metrics/time_window.go` line 27 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8Ma8E8jJZDqlxjk-K:-NQ8Ma8E8jJZDqlxjk-L:b-syerrc) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L27)):*
> ```Go
> 
> // slotter slot slices time window and maintains slot expiry and creation
> type slotter struct {
> ```

Per your comment, why not use `TimeWindow` directly?



_Code quote:_
```Go
slotter
```

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: all files reviewed, 4 unresolved discussions (waiting on @boqiu)

___
*[`util/metrics/time_window.go` line 11 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8LmvN1p06j2JoN3Cg:-NQ8RyvK1lVh4btV7nmF:b-9d1tfz) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L11)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is this interface required?
</blockquote></details>

`slot` is used to abstract different types of time window slot such as percentage slot and traffic hits slot (which I'm working on now),  so that `slotter` can operate on this interface commonly. 
___
*[`util/metrics/time_window.go` line 18 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8MURQ6Q2JSIVaOi-A:-NQ8SYD-1Wl2LzRrr7q6:bbhw2h1) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

bugfixed
___
*[`util/metrics/time_window.go` line 23 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8M-yj5LlgMAH56lPv:-NQ8Shwu5Cmi9zctcIpK:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not use `Before` instead of `After`?
</blockquote></details>

done
___
*[`util/metrics/time_window.go` line 27 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQ8Ma8E8jJZDqlxjk-K:-NQ8SzbUE0is8VQ9qaTv:b-oi7k8l) ([raw file](https://github.com/Conflux-Chain/confura/blob/9c0c0c4e4a7c2f121ad041a8789740896a592310/util/metrics/time_window.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Per your comment, why not use `TimeWindow` directly?
</blockquote></details>

Is `TimeWindow` some thirdparty lib or sth else? I'm working on a traffic collector which needs to reuse `slotter` logic for time window slot management.

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100#-:-NQA9UGEDsg1HqJaxdpE:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @wanliqun)

___
*[`util/metrics/percentage_time_window.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQACwsWB_vUgG81GJbn:-NQACwsWB_vUgG81GJbo:b-9e6m03) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/percentage_time_window.go#L72)):*
> ```Go
> // timeWindowPercentage implements Percentage interface to record recent percentage.
> type timeWindowPercentage struct {
> 	mu     sync.Mutex
> ```

Is it possible moving to `TimeWindow` to support concurrency in common?
___
*[`util/metrics/time_window.go` line 10 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQA9sZg9lwCnjvl4877:-NQA9sZg9lwCnjvl4878:b-977jwr) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L10)):*
> ```Go
> // time window slot data
> type SlotData interface {
> 	Accumulate(SlotData) SlotData
> ```

`Aggregate` is more meaningful.



_Code quote:_
```Go
Accumulate
```
___
*[`util/metrics/time_window.go` line 11 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQAA7MgBx4b1Sdn_YSh:-NQAA7MgBx4b1Sdn_YSi:bblpd5q) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L11)):*
> ```Go
> type SlotData interface {
> 	Accumulate(SlotData) SlotData
> 	Dissipate(SlotData) SlotData
> ```

How about use `Add` & `Sub` for readability?
___
*[`util/metrics/time_window.go` line 64 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQAAw9wBPG5UivCuT6Y:-NQAAw9wBPG5UivCuT6Z:b-m3j2s3) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L64)):*
> ```Go
> 
> // Aggregate aggregates the time window
> func (tw *TimeWindow) Aggregate() SlotData {
> ```

`Data` is more meaningful, since `Aggregate` is a verb.



_Code quote:_
```Go
Aggregate
```
___
*[`util/metrics/time_window.go` line 106 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQACfxq54slYVEXjLCb:-NQACfxq54slYVEXjLCc:b9c5cfd) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L106)):*
> ```Go
> 
> // getOrAddSlot gets the last slot or adds a new slot if the last one out of date.
> func (tw *TimeWindow) getOrAddSlot(now time.Time, data SlotData) (*slot, bool) {
> ```

could addOrUpdateSlot with `data`. 



_Code quote:_
```Go
getOrAddSlot
```

**Review by boqiu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: all files reviewed, 6 unresolved discussions (waiting on @wanliqun)

___
*[`util/metrics/percentage_time_window.go` line 100 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQADPeJ9SZynod3RK_c:-NQADPeJ9SZynod3RK_d:b-uze53f) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/percentage_time_window.go#L100)):*
> ```Go
> 
> 	aggdata := p.window.Aggregate().(twPercentageData)
> 	return (*percentageData)(&aggdata).value()
> ```

Pointer type conversion unnecessary?

**Review by wanliqun — COMMENTED** [review]
comments fixed

> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100#-:-NQOz_MS99VtaM3OMN1T:bonh1u5)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @boqiu)

___
*[`util/metrics/percentage_time_window.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQACwsWB_vUgG81GJbn:-NQOsU9a6ann11AbMpJK:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/percentage_time_window.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible moving to `TimeWindow` to support concurrency in common?
</blockquote></details>

done
___
*[`util/metrics/percentage_time_window.go` line 100 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQADPeJ9SZynod3RK_c:-NQOy1_P3L6YrqjfQ0eg:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/percentage_time_window.go#L100)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Pointer type conversion unnecessary?
</blockquote></details>

done
___
*[`util/metrics/time_window.go` line 10 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQA9sZg9lwCnjvl4877:-NQOsWUW-XPgQyd9Env8:btpexpf) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L10)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`Aggregate` is more meaningful.
</blockquote></details>

used `Add` instead
___
*[`util/metrics/time_window.go` line 11 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQAA7MgBx4b1Sdn_YSh:-NQOscJ038pdWpMatyWO:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L11)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about use `Add` & `Sub` for readability?
</blockquote></details>

done
___
*[`util/metrics/time_window.go` line 64 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQAAw9wBPG5UivCuT6Y:-NQOtZvH-KV3srQNOlw1:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L64)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`Data` is more meaningful, since `Aggregate` is a verb.
</blockquote></details>

done
___
*[`util/metrics/time_window.go` line 106 at r2](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQACfxq54slYVEXjLCb:-NQOxzquDe6u_Ev9k3--:b6nbdd4) ([raw file](https://github.com/Conflux-Chain/confura/blob/dc7c1cfdf122865866bea674e4696a6b4da382ff/util/metrics/time_window.go#L106)):*
> addOrUpdateSlot
done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[`util/metrics/time_window.go` line 51 at r3](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQP2WEE2FDC_XZMgV9T:-NQP2WEE2FDC_XZMgV9U:b-ono11) ([raw file](https://github.com/Conflux-Chain/confura/blob/2ab8cf6dca25f0814cffc0f333cf68d543728407/util/metrics/time_window.go#L51)):*
> ```Go
> 
> // Add adds data sample to time window
> func (tw *TimeWindow) Add(sample SlotData) {
> ```

Better to lock at the beginning of public method.
___
*[`util/metrics/time_window.go` line 63 at r3](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQP2K_sBl7n8luWX11X:-NQP2K_sBl7n8luWX11Y:b-ao791j) ([raw file](https://github.com/Conflux-Chain/confura/blob/2ab8cf6dca25f0814cffc0f333cf68d543728407/util/metrics/time_window.go#L63)):*
> ```Go
> // Data returns the aggregation data within the time window scope
> func (tw *TimeWindow) Data() SlotData {
> 	return tw.aggData
> ```

No (read) lock?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`util/metrics/time_window.go` line 51 at r3](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQP2WEE2FDC_XZMgV9T:-NQP6knCADDJ8Kd1uTow:b-896fix) ([raw file](https://github.com/Conflux-Chain/confura/blob/2ab8cf6dca25f0814cffc0f333cf68d543728407/util/metrics/time_window.go#L51)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to lock at the beginning of public method.
</blockquote></details>

Done.
___
*[`util/metrics/time_window.go` line 63 at r3](https://reviewable.io/reviews/Conflux-Chain/confura/100#-NQP2K_sBl7n8luWX11X:-NQP6kHy9iZyrfRx4t4_:b-896fix) ([raw file](https://github.com/Conflux-Chain/confura/blob/2ab8cf6dca25f0814cffc0f333cf68d543728407/util/metrics/time_window.go#L63)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

No (read) lock?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
