### PR TITLE
Add strategy v2 with multiple limit algorithms supported

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/confura/63)

### CODE REVIEW

**Comment by wanliqun** [comment]
Only `time window` and `token bucket` limit algorithms are supported for now.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/63)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[`util/rate/strategy_v2.go` line 19 at r1](https://reviewable.io/reviews/conflux-chain/confura/63#-NKRvVaVCyJTUvcQj2mh:-NKRvVaW5awVY040AOGl:b-jgdd4) ([raw file](https://github.com/conflux-chain/confura/blob/8502b2bb1fbc59e0f97cac43730b8667eadc290e/util/rate/strategy_v2.go#L19)):*
> ```Go
> 	LimitAlgoTimeWindow
> 	LimitAlgoTokenBucket
> 	LimitAlgoLastIndex
> ```

How about use `string` type for readability?
___
*[`util/rate/strategy_v2.go` line 104 at r1](https://reviewable.io/reviews/conflux-chain/confura/63#-NKRvx2a3A39UJZuG-m_:-NKRvx2a3A39UJZuG-ma:b-l27oui) ([raw file](https://github.com/conflux-chain/confura/blob/8502b2bb1fbc59e0f97cac43730b8667eadc290e/util/rate/strategy_v2.go#L104)):*
> ```Go
> }
> 
> type LimitRuleSet interface {
> ```

Not quite understand what this interface used for, and suggest to add necessary comment or use a more meaningful interface name.



_Code quote:_
```Go
LimitRuleSet
```

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/63)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`util/rate/strategy_v2.go` line 19 at r1](https://reviewable.io/reviews/conflux-chain/confura/63#-NKRvVaVCyJTUvcQj2mh:-NKS24I96esuZw5WYMZ-:bb6un1j) ([raw file](https://github.com/conflux-chain/confura/blob/8502b2bb1fbc59e0f97cac43730b8667eadc290e/util/rate/strategy_v2.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about use `string` type for readability?
</blockquote></details>

Done
___
*[`util/rate/strategy_v2.go` line 104 at r1](https://reviewable.io/reviews/conflux-chain/confura/63#-NKRvx2a3A39UJZuG-m_:-NKS28zQEaAmkGM5Qbn9:b-funolz) ([raw file](https://github.com/conflux-chain/confura/blob/8502b2bb1fbc59e0f97cac43730b8667eadc290e/util/rate/strategy_v2.go#L104)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Not quite understand what this interface used for, and suggest to add necessary comment or use a more meaningful interface name.
</blockquote></details>

Done

`LimitRuleSet` interface type is removed.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/confura/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
