### PR TITLE
Add RPC methods for CIP 1559

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/191)

### CODE REVIEW

**Comment by wanliqun** [comment]
eSpace debug RPC methods are not supported due to `web3go` sdk is not ready yet.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/191)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`rpc/cfx_api.go` line 474 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/191#-O-5W76y2YkBD5OF7n5I:-O-5W76y2YkBD5OF7n5J:b-vyzied) ([raw file](https://github.com/Conflux-Chain/confura/blob/14a105363b9ee2b413317a81d2304e41ddf84071/rpc/cfx_api.go#L474)):*
> ```Go
> ) (feeHistory *types.FeeHistory, err error) {
> 	cfx := GetCfxClientFromContext(ctx)
> 	return cfx.GetFeeHistory(blockCount, lastEpoch, rewardPercentiles)
> ```

Any limitations for the length of `rewardPercentiles`?

**Comment by wanliqun** [comment]
*[`rpc/cfx_api.go` line 474 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/191#-O-5W76y2YkBD5OF7n5I:-O-5YzLFEPMDIy7rGXcf:belctjc) ([raw file](https://github.com/Conflux-Chain/confura/blob/14a105363b9ee2b413317a81d2304e41ddf84071/rpc/cfx_api.go#L474)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Any limitations for the length of `rewardPercentiles`?
</blockquote></details>

This argument is optional, which means we can pass an empty array. Also there is no max limit per to existing Ethereum RPC specification.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/confura/191)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Comment by wanliqun** [comment]
*[`rpc/cfx_api.go` line 474 at r1](https://reviewable.io/reviews/Conflux-Chain/confura/191#-O-5W76y2YkBD5OF7n5I:-O-5iLYb1TgHlPT1BpVY:byjn8jv) ([raw file](https://github.com/Conflux-Chain/confura/blob/14a105363b9ee2b413317a81d2304e41ddf84071/rpc/cfx_api.go#L474)):*
<details><summary><i>Previously, wanliqun (Liqun) wrote…</i></summary><blockquote>

This argument is optional, which means we can pass an empty array. Also there is no max limit per to existing Ethereum RPC specification.
</blockquote></details>

Enforce a hard limit for `rewardPercentitles` length to be 50.

**Pull request merged**
